# Generated by Django 5.1.3 on 2024-11-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dozo', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2),
        ),
    ]
