# Generated by Django 5.1.3 on 2024-11-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dozo', '0008_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2),
        ),
    ]
