# Generated by Django 5.1.3 on 2024-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dozo', '0012_remove_cart_product_id_remove_cart_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
