# Generated by Django 5.1.3 on 2024-11-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dozo', '0014_alter_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default=0, max_length=30, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dozo.estado'),
        ),
    ]
